import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { getServerSession } from "next-auth/next";
import MySessionProvider from "@/Providers/MySessionProvider";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { GlobalConvProvider } from "@/Providers/ContextApi";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
        <GlobalConvProvider>
          <MySessionProvider session={session}>
            <Header />
            {children}
          </MySessionProvider>
        </GlobalConvProvider>
      </body>
    </html>
  );
}
